# Generated by Django 3.0.8 on 2021-01-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200920_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullorder',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='fullorder',
            old_name='state',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='division',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.AlterField(
            model_name='fullorder',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
